export const EXCHANGE_CONTRACT_ADDRESS =
  "0x5E28Fe4Be517EAe4092aB6547B287349dF950383";
export const USDT_CONTRACT_ADDRESS =
  "0x96711f91eb24a3D1dfA3eD308A84380DFD4CC1c7";
export const WRONG_CHAIN_MESSAGE = process.env.REACT_APP_WRONG_CHAIN_MESSAGE;
export const SUPPORTED_CHAIN_IDS = process.env.REACT_APP_SUPPORTED_CHAIN_IDS;
//ethereum

export const ETHEREUM_CHAIN_ID = process.env.REACT_APP_ETHEREUM_CHAIN_ID;
export const CONTRACT_ADDRESS_CAPX_USDT_ETHEREUM =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_USDT_ETHEREUM;
export const CONTRACT_ADDRESS_CAPX_EXCHANGE_ETHEREUM =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_EXCHANGE_ETHEREUM;
export const GRAPHAPIURL_WRAPPED_ETHEREUM =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_ETHEREUM;
export const GRAPHAPIURL_EXCHANGE_ETHEREUM =
  process.env.REACT_APP_GRAPHAPIURL_EXCHANGE_ETHEREUM;
export const GRAPHAPIURL_MASTER_ETHEREUM =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_ETHEREUM;
export const EXPLORER_ETHEREUM = process.env.REACT_APP_EXPLORER_ETHEREUM;

//matic
export const MATIC_CHAIN_ID = process.env.REACT_APP_MATIC_CHAIN_ID;
export const CONTRACT_ADDRESS_CAPX_USDT_MATIC =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_USDT_MATIC;
export const CONTRACT_ADDRESS_CAPX_EXCHANGE_MATIC =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_EXCHANGE_MATIC;
export const GRAPHAPIURL_WRAPPED_MATIC =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_MATIC;
export const GRAPHAPIURL_EXCHANGE_MATIC =
  process.env.REACT_APP_GRAPHAPIURL_EXCHANGE_MATIC;
export const GRAPHAPIURL_MASTER_MATIC =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_MATIC;
export const EXPLORER_MATIC = process.env.REACT_APP_EXPLORER_MATIC;

//bsc
export const BSC_CHAIN_ID = process.env.REACT_APP_BSC_CHAIN_ID;
export const CONTRACT_ADDRESS_CAPX_USDT_BSC =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_USDT_BSC;
export const CONTRACT_ADDRESS_CAPX_EXCHANGE_BSC =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_EXCHANGE_BSC;
export const GRAPHAPIURL_WRAPPED_BSC =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_BSC;
export const GRAPHAPIURL_EXCHANGE_BSC =
  process.env.REACT_APP_GRAPHAPIURL_EXCHANGE_BSC;
export const GRAPHAPIURL_MASTER_BSC =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_BSC;
export const EXPLORER_BSC = process.env.REACT_APP_EXPLORER_BSC;

//avalanche
export const AVALANCHE_CHAIN_ID = process.env.REACT_APP_AVALANCHE_CHAIN_ID;
export const CONTRACT_ADDRESS_CAPX_USDT_AVALANCHE =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_USDT_AVALANCHE;
export const CONTRACT_ADDRESS_CAPX_EXCHANGE_AVALANCHE =
  process.env.REACT_APP_CONTRACT_ADDRESS_CAPX_EXCHANGE_AVALANCHE;
export const GRAPHAPIURL_WRAPPED_AVALANCHE =
  process.env.REACT_APP_GRAPHAPIURL_WRAPPED_AVALANCHE;
export const GRAPHAPIURL_EXCHANGE_AVALANCHE =
  process.env.REACT_APP_GRAPHAPIURL_EXCHANGE_AVALANCHE;
export const GRAPHAPIURL_MASTER_AVALANCHE =
  process.env.REACT_APP_GRAPHAPIURL_MASTER_AVALANCHE;
export const EXPLORER_AVALANCHE = process.env.REACT_APP_EXPLORER_AVALANCHE;
